[general]
# import = ["<string>"]
live_config_reload = false
ipc_socket = false

[window]
# blur = true
decorations = "None"
opacity = 0.92
dynamic_title = false

[font]
normal = { family = "DejaVuSansM Nerd Font Mono", style = "bold" }
size = 11
builtin_box_drawing = true

# ã‚¢ãƒ‹ãƒ¡ã€Œã‹ãã‚„æ§˜ã¯å‘Šã‚‰ã›ãŸã„-ã‚¦ãƒ«ãƒˆãƒ©ãƒ­ãƒãƒ³ãƒ†ã‚£ãƒƒã‚¯-ã€ä¸»é¡Œæ­Œ
# î¬î®«î® î¬¬
# î¯˜ îª„ î¬³
# ğŸš«ğŸš«ğŸš«

[selection]
save_to_clipboard = true

[mouse]
hide_when_typing = true

[colors]
# transparent_background_colors = true
draw_bold_text_with_bright_colors = false

[colors.primary]
# background = '#111129'
# foreground = '#abb2bf'

[colors.normal]
black   = '#5c6370'
red     = '#e06c75'
green   = '#98c379'
yellow  = '#e5c07b'
blue    = '#61afef'
magenta = '#c678dd'
cyan    = '#56b6c2'
white   = '#abb2bf'

[colors.bright]
black   = '#5c6370'
red     = '#be5046'
green   = '#98c379'
yellow  = '#d19a66'
blue    = '#61afef'
magenta = '#c678dd'
cyan    = '#56b6c2'
white   = '#e6efff'

